// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiTenantDbContext.Data.Customer;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MultiTenantDbContext.Data.Customer.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20250425163056_AddVechiclesTable")]
    partial class AddVechiclesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MultiTenantDbContext.Data.Customer.Data", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Data");
                });

            modelBuilder.Entity("MultiTenantDbContext.Data.Customer.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Vehicles", (string)null);

                    b.HasDiscriminator<int>("VehicleType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MultiTenantDbContext.Data.Customer.Car", b =>
                {
                    b.HasBaseType("MultiTenantDbContext.Data.Customer.Vehicle");

                    b.Property<int>("NumberOfDoors")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("MultiTenantDbContext.Data.Customer.Motorcycle", b =>
                {
                    b.HasBaseType("MultiTenantDbContext.Data.Customer.Vehicle");

                    b.Property<bool>("HasSidecar")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("MultiTenantDbContext.Data.Customer.Truck", b =>
                {
                    b.HasBaseType("MultiTenantDbContext.Data.Customer.Vehicle");

                    b.Property<int>("LoadCapacity")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(1);
                });
#pragma warning restore 612, 618
        }
    }
}
